name: java-ci

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout the code
              uses: actions/checkout@v7
            
            - name: Setup Java
              uses: actions/setup-java@v6
              with:
                java-version: '21'
                distribution: 'temurin'

            - name: Run tests
              run: ./mvnw test
            
            - name: Build package
              run: ./mvnw package

            - name: Upload JAR
              uses: actions/upload-artifact@v4
              with: 
                name: calculator
                path: target/*.jar
